export { default as NavBar } from './NavBar/NavBar.jsx'
export { default as Product } from './Product.jsx'
export { default as Cart } from './Cart/Cart.jsx'
export { default as Checkout } from './CheckoutForm/Checkout/Checkout.jsx'
export { default as Footer } from './Footer/Footer.jsx'